import { Product, Collection } from "@/types";

export const collections: Collection[] = [
  {
    id: "funny-unfiltered",
    name: "Funny & Unfiltered",
    description: "Because life's too short for boring mugs",
    image: "/images/collections/funny.jpg",
    color: "#E91E8C",
    textColor: "#ffffff",
    slug: "funny-unfiltered",
  },
  {
    id: "faith-inspiration",
    name: "Faith & Inspiration",
    description: "Start your morning with purpose",
    image: "/images/collections/faith.jpg",
    color: "#F0A500",
    textColor: "#ffffff",
    slug: "faith-inspiration",
  },
  {
    id: "boss-business",
    name: "Boss & Business",
    description: "For the empire builders and go-getters",
    image: "/images/collections/boss.jpg",
    color: "#1B2A4A",
    textColor: "#ffffff",
    slug: "boss-business",
  },
  {
    id: "black-excellence",
    name: "Black Excellence",
    description: "Celebrate culture, pride, and power",
    image: "/images/collections/excellence.jpg",
    color: "#7B4FBE",
    textColor: "#ffffff",
    slug: "black-excellence",
  },
  {
    id: "pet-lovers",
    name: "Pet Lovers",
    description: "Because fur babies deserve top billing",
    image: "/images/collections/pets.jpg",
    color: "#00B4B4",
    textColor: "#ffffff",
    slug: "pet-lovers",
  },
  {
    id: "holiday-seasonal",
    name: "Holiday & Seasonal",
    description: "Season's greetings in every sip",
    image: "/images/collections/holiday.jpg",
    color: "#FF6B35",
    textColor: "#ffffff",
    slug: "holiday-seasonal",
  },
  {
    id: "wedding-anniversary",
    name: "Wedding & Anniversary",
    description: "For the couples who sip together",
    image: "/images/collections/wedding.jpg",
    color: "#E91E8C",
    textColor: "#ffffff",
    slug: "wedding-anniversary",
  },
  {
    id: "survivor-strong",
    name: "Survivor Strong",
    description: "Strength, resilience, and celebration",
    image: "/images/collections/survivor.jpg",
    color: "#00B4B4",
    textColor: "#ffffff",
    slug: "survivor-strong",
  },
  {
    id: "design-your-own",
    name: "Design Your Own",
    description: "Your imagination, our mugs",
    image: "/images/collections/custom.jpg",
    color: "#1B2A4A",
    textColor: "#F0A500",
    slug: "design-your-own",
  },
];

export const products: Product[] = [
  {
    id: "mug-001",
    name: "I Speak Fluent Sarcasm",
    description: "11 oz white ceramic mug, dishwasher safe",
    price: 24.99,
    image: "/images/products/sarcasm-mug.jpg",
    category: "funny-unfiltered",
    badge: "Bestseller",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "black-11oz", name: "Black 11oz", price: 26.99 },
      { id: "color-handle-11oz", name: "Color Handle 11oz", price: 27.99 },
    ],
  },
  {
    id: "mug-002",
    name: "Blessed & Caffeinated",
    description: "Start every morning with faith and flavor",
    price: 24.99,
    image: "/images/products/blessed-mug.jpg",
    category: "faith-inspiration",
    badge: "Fan Favorite",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "color-handle-11oz", name: "Color Handle 11oz", price: 27.99 },
    ],
  },
  {
    id: "mug-003",
    name: "Boss Lady Building My Empire",
    description: "For the woman who runs the show",
    price: 24.99,
    image: "/images/products/boss-mug.jpg",
    category: "boss-business",
    badge: "New",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "black-11oz", name: "Black 11oz", price: 26.99 },
    ],
  },
  {
    id: "mug-004",
    name: "Minding My Black-Owned Business",
    description: "Celebrating culture and entrepreneurship",
    price: 24.99,
    image: "/images/products/excellence-mug.jpg",
    category: "black-excellence",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "black-11oz", name: "Black 11oz", price: 26.99 },
    ],
  },
  {
    id: "mug-005",
    name: "Best Dog Mom Ever",
    description: "For the fur mama who loves unconditionally",
    price: 24.99,
    image: "/images/products/dog-mug.jpg",
    category: "pet-lovers",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "color-handle-11oz", name: "Color Handle 11oz", price: 27.99 },
    ],
  },
  {
    id: "mug-006",
    name: "'Tis The Season To Be Jolly",
    description: "Spread holiday cheer one sip at a time",
    price: 24.99,
    image: "/images/products/holiday-mug.jpg",
    category: "holiday-seasonal",
    badge: "Holiday Pick",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "color-handle-11oz", name: "Color Handle 11oz", price: 27.99 },
    ],
  },
  {
    id: "mug-007",
    name: "Mr. & Mrs. Forever",
    description: "The perfect wedding gift or keepsake",
    price: 29.99,
    image: "/images/products/wedding-mug.jpg",
    category: "wedding-anniversary",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 29.99 },
    ],
  },
  {
    id: "mug-008",
    name: "Nice Until Proven Naughty",
    description: "Keeping it real since forever",
    price: 24.99,
    image: "/images/products/naughty-mug.jpg",
    category: "funny-unfiltered",
    variants: [
      { id: "white-11oz", name: "White 11oz", price: 24.99 },
      { id: "black-11oz", name: "Black 11oz", price: 26.99 },
      { id: "color-handle-11oz", name: "Color Handle 11oz", price: 27.99 },
    ],
  },
];

export const featuredProducts = products.slice(0, 4);
